[platformio]
default_envs = x4
extra_configs = platformio.local.ini

[engine]
version = 0.1.0

[base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_upload.offset_address = 0x10000

board_build.flash_mode = dio
board_build.flash_size = 16MB
board_build.partitions = partitions.csv

build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DEINK_DISPLAY_SINGLE_BUFFER_MODE=1
  -DDISABLE_FS_H_WARNING=1
  -DDESTRUCTOR_CLOSES_FILE=1
  -std=gnu++2a
  -DUSE_UTF8_LONG_NAMES=1
  -DPUZZLE_GAME_VERSION=\"${engine.version}\"
  -fno-exceptions

build_unflags =
  -std=gnu++11
  -fexceptions

lib_deps =
  BatteryMonitor=symlink://../community-sdk/libs/hardware/BatteryMonitor
  InputManager=symlink://../community-sdk/libs/hardware/InputManager
  EInkDisplay=symlink://../community-sdk/libs/display/EInkDisplay
  SDCardManager=symlink://../community-sdk/libs/hardware/SDCardManager
  bblanchon/ArduinoJson @ 7.4.2

[env:x4]
extends = base
build_flags =
  ${base.build_flags}
  -DENABLE_SERIAL_LOG=1

[env:x3]
extends = base
build_flags =
  ${base.build_flags}
  -DENABLE_SERIAL_LOG=1
  -DXTEINK_PANEL_X3=1
