"""Regenerates src/ui/IconAssetsData.h from assets/icons/* assets.

Run before every build (build_and_flash.bat does this automatically) so
growing the icon collection - regenerating more words via ebookcreator's
generate_puzzle_icons.py - never needs manual header wiring: drop the new
source PNG files into assets/icon_sources/ and rebuild.

Icons are embedded directly in firmware (PROGMEM byte arrays), not loaded
from the SD card. Each icon has a 192x192 2-bit grayscale word image and a
32x32 1-bit counting image. At ~9.1KB per icon, a 500-word vocabulary is
still expected to fit in the ~6.5MB app partition, but with less headroom
than the earlier 96x96-only format.

Usage:
  python tools/bundle_icons.py
"""

import re
import sys
from pathlib import Path

ICONS_DIR = Path(__file__).parent.parent / "assets" / "icons"
OUTPUT = Path(__file__).parent.parent / "src" / "ui" / "IconAssetsData.h"
BYTES_PER_LINE = 20


def format_bytes(data: bytes) -> str:
    rows = []
    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        rows.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(rows)


def main() -> None:
    if not ICONS_DIR.is_dir():
        print(f"error: icon directory does not exist: {ICONS_DIR}", file=sys.stderr)
        raise SystemExit(1)

    word_icons: dict[str, Path] = {}
    count_icons: dict[str, Path] = {}
    for path in sorted(ICONS_DIR.glob("*.word.gray.bin")):
        m = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_]*)\.word\.gray\.bin", path.name)
        if not m:
            continue
        word_icons[m.group(1)] = path

    for path in sorted(ICONS_DIR.glob("*.count.1bit.bin")):
        m = re.fullmatch(r"([A-Za-z_][A-Za-z0-9_]*)\.count\.1bit\.bin", path.name)
        if not m:
            continue
        count_icons[m.group(1)] = path

    if not word_icons:
        print(f"error: no word icon .bin files found in {ICONS_DIR}", file=sys.stderr)
        raise SystemExit(1)
    missing_count = sorted(set(word_icons) - set(count_icons))
    missing_word = sorted(set(count_icons) - set(word_icons))
    if missing_count or missing_word:
        if missing_count:
            print(f"error: missing count assets for: {', '.join(missing_count)}", file=sys.stderr)
        if missing_word:
            print(f"error: missing word assets for: {', '.join(missing_word)}", file=sys.stderr)
        raise SystemExit(1)

    lines = [
        "// AUTO-GENERATED by tools/bundle_icons.py - do not edit by hand.",
        "// Regenerate after adding/changing files in assets/icons/.",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <pgmspace.h>",
        "",
        "namespace puzzle::ui {",
        "",
    ]

    entries = []
    total_bytes = 0
    for icon_id in sorted(word_icons):
        word_data = word_icons[icon_id].read_bytes()
        count_data = count_icons[icon_id].read_bytes()
        expected_word_bytes = 192 * 192 // 4
        expected_count_bytes = 32 * 32 // 8
        if len(word_data) != expected_word_bytes:
            print(
                f"error: {word_icons[icon_id].name} is {len(word_data)} bytes; expected "
                f"{expected_word_bytes} bytes for a 192x192 2-bit image",
                file=sys.stderr,
            )
            raise SystemExit(1)
        if len(count_data) != expected_count_bytes:
            print(
                f"error: {count_icons[icon_id].name} is {len(count_data)} bytes; expected "
                f"{expected_count_bytes} bytes for a 32x32 1-bit image",
                file=sys.stderr,
            )
            raise SystemExit(1)
        total_bytes += len(word_data) + len(count_data)
        lines.append(f"static const uint8_t kIcon_{icon_id}_word[] PROGMEM = {{")
        lines.append(format_bytes(word_data))
        lines.append("};")
        lines.append("")
        lines.append(f"static const uint8_t kIcon_{icon_id}_count[] PROGMEM = {{")
        lines.append(format_bytes(count_data))
        lines.append("};")
        lines.append("")
        entries.append(icon_id)

    lines += [
        "struct IconAssetEntry {",
        "  const char* iconId;",
        "  const uint8_t* wordData;",
        "  const uint8_t* countData;",
        "  uint16_t wordBytes;",
        "  uint16_t countBytes;",
        "};",
        "",
        "static const IconAssetEntry kIconAssetTable[] = {",
    ]
    for icon_id in entries:
        lines.append(
            f'    {{"{icon_id}", kIcon_{icon_id}_word, kIcon_{icon_id}_count, '
            f"sizeof(kIcon_{icon_id}_word), sizeof(kIcon_{icon_id}_count)}},"
        )
    lines += [
        "};",
        "static constexpr size_t kIconAssetCount = sizeof(kIconAssetTable) / sizeof(kIconAssetTable[0]);",
        "",
        "}  // namespace puzzle::ui",
        "",
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT}")
    print(f"{len(entries)} icons bundled, {total_bytes} bytes embedded")


if __name__ == "__main__":
    main()
